# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets_Employee_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assetid', models.CharField(default='AS000', max_length=120)),
                ('Employeeid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assets_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSETID', models.CharField(default='AS000', max_length=120, unique=True)),
                ('DEVICE', models.CharField(choices=[('Laptop', 'Laptop'), ('Mouse', 'Mouse'), ('Monitor', 'Monitor'), ('CPU', 'CPU'), ('Headset', 'Headset'), ('Mobile-Phone', 'Mobile Phone')], default='Laptop', max_length=13)),
                ('MANUFACTURE', models.DateField()),
                ('SNO', models.IntegerField(default=0)),
                ('WARRANTYEXPIRY', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField(unique=True)),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=60)),
                ('Company_Name', models.CharField(default='Polyglot', max_length=120)),
                ('Employee_Email', models.EmailField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Table',
            fields=[
                ('Userid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=8)),
            ],
        ),
    ]
