# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetMP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='Company_Name',
            field=models.CharField(default='iTalent', max_length=120),
        ),
    ]
